name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /root/hair_bot
            git pull
            docker compose up -d --build
            docker compose exec api alembic upgrade head
